# Generated by Django 4.1.5 on 2023-07-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("completed", "completed"),
                    ("canceled", "canceled"),
                    ("Accepted", "Accepted"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
